apiVersion: batch/v1
kind: Job
metadata:
  name: farmbot-water
spec:
  template:
    spec:
      containers:
        - name: farmbot-water-garden
          image: eu.gcr.io/farmbot-b787d/water-garden:0.1.0
          imagePullPolicy: IfNotPresent
      restartPolicy: Never
  backoffLimit: 4
