apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: farmbot-water-garden-daily
spec:
  schedule: "30 11 * * 1-5"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: farmbot-water-garden
              image: eu.gcr.io/farmbot-b787d/water-garden
              imagePullPolicy: IfNotPresent
          restartPolicy: Never
